# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ThaMovieDB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.5'
  pod 'SDWebImage', '~> 4.0'

  target 'ThaMovieDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ThaMovieDBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
