//
//  UpcomingMoviesListInteractor.swift
//  TheMovieDB
//
//  Created by Tiago Chaves on 03/10/18.
//  Copyright (c) 2018 TiagoChaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UpcomingMoviesListBusinessLogic
{
    func getGenres(request: UpcomingMoviesList.GenresList.Request)
    func getUpcomingMovies(request: UpcomingMoviesList.MoviesList.Request)
    func getFilteredUpcomingMoview(request:UpcomingMoviesList.FilteredMovies.Request)
    func saveUpcomingMovie(request:UpcomingMoviesList.MovieDetail.Request)
}

protocol UpcomingMoviesListDataStore
{
    var upcomingMovie:DisplayUpcomingMovie? { get set }
}

class UpcomingMoviesListInteractor: UpcomingMoviesListBusinessLogic, UpcomingMoviesListDataStore
{
    var presenter: UpcomingMoviesListPresentationLogic?
    var worker: UpcomingMoviesListWorker?
    var genreWorker: GenresWorker?
    var upcomingMovie: DisplayUpcomingMovie?
    
    // MARK: - UpcomingMoviesListBusinessLogic
    
    func getGenres(request: UpcomingMoviesList.GenresList.Request) {
        
        let networkWorker = GenresNetworkWorker()
        genreWorker = GenresWorker(networkWorker, nil)
        genreWorker?.getGenresList(completionHandler: { (genreData, error) in
            
            if error == nil, let genreData = genreData {
                
                Genre.add(genres: genreData)
            }
        })
    }
    
    func getUpcomingMovies(request: UpcomingMoviesList.MoviesList.Request)
    {
        let networkWorker = UpcomingMoviesNetworkWorker()
        worker = UpcomingMoviesListWorker(networkWorker)
        worker?.getUpcomingMovies(ofPage: request.page, completionHandler: { (upcomingMovieResult,error) in
            
            let response:UpcomingMoviesList.MoviesList.Response
            
            if error == nil, let result = upcomingMovieResult {
                response = UpcomingMoviesList.MoviesList.Response(upcomingMoviesResult:result, error:nil)
            }else{
                response = UpcomingMoviesList.MoviesList.Response(upcomingMoviesResult:nil, error:error)
            }
            
            self.presenter?.presentUpcomingMovies(response:response)
        })
    }
    
    func getFilteredUpcomingMoview(request: UpcomingMoviesList.FilteredMovies.Request) {
        let response = UpcomingMoviesList.FilteredMovies.Response(text:request.text, upcomingMovies: request.upcomingMovies)
        presenter?.presentFilteredUpcomingMovies(response:response)
    }
    
    func saveUpcomingMovie(request: UpcomingMoviesList.MovieDetail.Request) {
        self.upcomingMovie = request.upcomingMovie
        let response = UpcomingMoviesList.MovieDetail.Response()
        presenter?.presentUpcomingMovieDetail(response: response)
    }
}
