//
//  UpcomingMoviesListRouter.swift
//  TheMovieDB
//
//  Created by Tiago Chaves on 03/10/18.
//  Copyright (c) 2018 TiagoChaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol UpcomingMoviesListRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol UpcomingMoviesListDataPassing
{
  var dataStore: UpcomingMoviesListDataStore? { get }
}

class UpcomingMoviesListRouter: NSObject, UpcomingMoviesListRoutingLogic, UpcomingMoviesListDataPassing
{
  weak var viewController: UpcomingMoviesListViewController?
  var dataStore: UpcomingMoviesListDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: UpcomingMoviesListViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: UpcomingMoviesListDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
