//
//  UpcomingMoviesListWorker.swift
//  TheMovieDB
//
//  Created by Tiago Chaves on 03/10/18.
//  Copyright (c) 2018 TiagoChaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class UpcomingMoviesListWorker{
    
    var worker:UpcomingMoviesListWorkerProtocol
    
    init(_ worker:UpcomingMoviesListWorkerProtocol){
        self.worker = worker
    }
    
    func getUpcomingMovies(ofPage page:Int, completionHandler:@escaping (UpcomingMovieResult?,Error?) -> Void){
        
        worker.getUpcomingMovies(ofPage: page) { (upcomingMovies: () throws -> UpcomingMovieResult) -> Void in
            do {
                let upcomingMovies = try upcomingMovies()
                completionHandler(upcomingMovies,nil)
            }catch let error{
                completionHandler(nil,error)
            }
        }
    }
}

protocol UpcomingMoviesListWorkerProtocol {
    func getUpcomingMovies(ofPage page:Int, completionHandler:@escaping (() throws -> UpcomingMovieResult) -> Void)
}
