//
//  UpcomingMoviesListModels.swift
//  TheMovieDB
//
//  Created by Tiago Chaves on 03/10/18.
//  Copyright (c) 2018 TiagoChaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum UpcomingMoviesList
{
    // MARK: Use cases
    
    enum MoviesList
    {
        struct Request
        {
            var page:Int
        }
        struct Response
        {
            var upcomingMoviesResult:UpcomingMovieResult?
            var error:Error?
        }
        struct ViewModel
        {
            var upcomingMovies:DisplayUpcomingMoviesResult?
            var error:Error?
        }
    }
    
    enum FilteredMovies{
        
        struct Request {
            var text:String
        }
        struct Response {
            var text:String
        }
        struct ViewModel {
            var filteredUpcomingMovies:DisplayUpcomingMoviesResult?
        }
    }
}

struct DisplayUpcomingMoviesResult{
    let nextPage:Int
    let upcomingMovies:[DisplayUpcomingMovie]
}

struct DisplayUpcomingMovie {
    let posterPath:String
    let backdropPath:String
    let overview:String
    let releaseDate:String
    let genre:[String]
    let title:String
}
