//
//  UpcomingMovieDetailPresenter.swift
//  TheMovieDB
//
//  Created by Tiago Chaves on 03/10/18.
//  Copyright (c) 2018 TiagoChaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UpcomingMovieDetailPresentationLogic
{
  func presentSomething(response: UpcomingMovieDetail.Something.Response)
}

class UpcomingMovieDetailPresenter: UpcomingMovieDetailPresentationLogic
{
  weak var viewController: UpcomingMovieDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: UpcomingMovieDetail.Something.Response)
  {
    let viewModel = UpcomingMovieDetail.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
