//
//  UpcomingMovieDetailInteractor.swift
//  TheMovieDB
//
//  Created by Tiago Chaves on 03/10/18.
//  Copyright (c) 2018 TiagoChaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UpcomingMovieDetailBusinessLogic
{
    func getMovieDetail(request: UpcomingMovieDetail.MovieDetail.Request)
}

protocol UpcomingMovieDetailDataStore
{
    var upcomingMovie:DisplayUpcomingMovie? { get set }
}

class UpcomingMovieDetailInteractor: UpcomingMovieDetailBusinessLogic, UpcomingMovieDetailDataStore
{
    var presenter: UpcomingMovieDetailPresentationLogic?
    var worker: UpcomingMovieDetailWorker?
    var upcomingMovie:DisplayUpcomingMovie?
    
    // MARK: Do something
    
    func getMovieDetail(request: UpcomingMovieDetail.MovieDetail.Request) {
        
        let response = UpcomingMovieDetail.MovieDetail.Response(upcomingMoviesDetail: self.upcomingMovie!)
        presenter?.presentMovieDetail(response: response)
    }
}
