//
//  UpcomingMovieDetailModels.swift
//  TheMovieDB
//
//  Created by Tiago Chaves on 03/10/18.
//  Copyright (c) 2018 TiagoChaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum UpcomingMovieDetail
{
    // MARK: Use cases
    
    enum MovieDetail
    {
        struct Request
        {
            var overviewFont:UIFont
            var overviewWidth:CGFloat
        }
        struct Response
        {
            var overviewFont:UIFont
            var overviewWidth:CGFloat
            var upcomingMoviesDetail:DisplayUpcomingMovie
        }
        struct ViewModel
        {
            var upcomingMoviesDetail:DisplayUpcomingMovie
            var overviewHeightConstraint:CGFloat
        }
    }
}
