//
//  UpcomingMovieDetailInteractor.swift
//  ThaMovieDB
//
//  Created by Tiago Chaves on 03/10/18.
//  Copyright (c) 2018 TiagoChaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UpcomingMovieDetailBusinessLogic
{
  func doSomething(request: UpcomingMovieDetail.Something.Request)
}

protocol UpcomingMovieDetailDataStore
{
  //var name: String { get set }
}

class UpcomingMovieDetailInteractor: UpcomingMovieDetailBusinessLogic, UpcomingMovieDetailDataStore
{
  var presenter: UpcomingMovieDetailPresentationLogic?
  var worker: UpcomingMovieDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: UpcomingMovieDetail.Something.Request)
  {
    worker = UpcomingMovieDetailWorker()
    worker?.doSomeWork()
    
    let response = UpcomingMovieDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
