//
//  UpcomingMoviesListInteractor.swift
//  ThaMovieDB
//
//  Created by Tiago Chaves on 03/10/18.
//  Copyright (c) 2018 TiagoChaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UpcomingMoviesListBusinessLogic
{
  func doSomething(request: UpcomingMoviesList.Something.Request)
}

protocol UpcomingMoviesListDataStore
{
  //var name: String { get set }
}

class UpcomingMoviesListInteractor: UpcomingMoviesListBusinessLogic, UpcomingMoviesListDataStore
{
  var presenter: UpcomingMoviesListPresentationLogic?
  var worker: UpcomingMoviesListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: UpcomingMoviesList.Something.Request)
  {
    worker = UpcomingMoviesListWorker()
    worker?.doSomeWork()
    
    let response = UpcomingMoviesList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
