//
//  UpcomingMoviesListPresenter.swift
//  ThaMovieDB
//
//  Created by Tiago Chaves on 03/10/18.
//  Copyright (c) 2018 TiagoChaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UpcomingMoviesListPresentationLogic
{
  func presentSomething(response: UpcomingMoviesList.Something.Response)
}

class UpcomingMoviesListPresenter: UpcomingMoviesListPresentationLogic
{
  weak var viewController: UpcomingMoviesListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: UpcomingMoviesList.Something.Response)
  {
    let viewModel = UpcomingMoviesList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
