//
//  UpcomingMoviesListWorkerTests.swift
//  TheMovieDB
//
//  Created by Tiago Chaves on 06/10/2018.
//  Copyright (c) 2018 TiagoChaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TheMovieDB
import XCTest

class UpcomingMoviesListWorkerTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: UpcomingMoviesListWorker!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        setupUpcomingMoviesListWorker()
    }
    
    override func tearDown()
    {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupUpcomingMoviesListWorker()
    {
        sut = UpcomingMoviesListWorker(UpcomingMoviesNetworkWorkerSpy())
    }
    
    // MARK: Test doubles
    
    class UpcomingMoviesNetworkWorkerSpy:UpcomingMoviesNetworkWorker {
        
        var networkWorkerCalled = false
        override func getUpcomingMovies(ofPage page: Int, completionHandler: @escaping (() throws -> UpcomingMovieResult) -> Void) {
            
            networkWorkerCalled = true
            completionHandler { return Seeds.UpcomingMoviesAPIList.result }
        }
    }
    
    // MARK: Tests
    
    func testGetUpcomingMoviesListShouldBeReturnedFromAPI()
    {
        let upcomingMoviesNetworkSpy = sut.worker as! UpcomingMoviesNetworkWorkerSpy
        
        let expect = expectation(description: "Wait for API result to return")
        sut.getUpcomingMovies(ofPage: 1, completionHandler: { (upcomingMovies, error) in
            expect.fulfill()
        })
        waitForExpectations(timeout: 1.1)
        
        XCTAssertTrue(upcomingMoviesNetworkSpy.networkWorkerCalled, "getUpcomingMovies result should ask API for the list")
    }
}
